#root -q "RecoEffCalculator_TTreeReader.C(\"nom.yaml\",\"data_aa\")"
root -q "RecoEffCalculator_TTreeReader.C(\"nom.yaml\",\"photon10_aa\")"
root -q "RecoEffCalculator_TTreeReader.C(\"nom.yaml\",\"photon20_aa\")"
#root -q "RecoEffCalculator_TTreeReader.C(\"nom.yaml\",\"jet10_aa\")"
#root -q "RecoEffCalculator_TTreeReader.C(\"nom.yaml\",\"jet20_aa\")"
